DROP DATABASE IF EXISTS j4jti3obcm1stb2r;

CREATE DATABASE j4jti3obcm1stb2r;

USE j4jti3obcm1stb2r;

CREATE TABLE burgers (

  id INT NOT NULL AUTO_INCREMENT,
  burger_name VARCHAR(200) NOT NULL,
  devoured BOOLEAN NOT NULL DEFAULT FALSE,
  date TIMESTAMP,
  PRIMARY KEY (id)
);
